# Generated by Django 5.0.1 on 2024-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='audio_title'),
        ),
    ]
