# Generated by Django 5.0.1 on 2024-03-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_rename_audio_audiobookmodel'),
        ('book', '0002_alter_book_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
